sudo: false

rvm:
  - 2.2
  - 2.3.0

# cache:
#   directories:
#   - $HOME/gnatsd

before_install:
  - bash ./scripts/install_gnatsd.sh

before_script:
  - export PATH=$HOME/gnatsd:$PATH

sudo: required
dist: trusty
